# Generated by Django 4.0 on 2024-02-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_username_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
